### ISSUE TITLE
Add support for code snippets

### ISSUE THREAD

**Issue by ChillerDragon** [tyage/slack-patron#100]
Text formatted with \`\`\` should also be presented in a code block in the web preview.

slack:

![image](https://user-images.githubusercontent.com/20344300/75864018-ae45a700-5e01-11ea-94e5-c7c1062a23e2.png)

slack-patron web:

![image](https://user-images.githubusercontent.com/20344300/75864052-bac9ff80-5e01-11ea-9a54-b0872cec672a.png)

**Comment by tyage** [comment]
this issue should have been resolved with #127
