### ISSUE TITLE
Font-family behind proxypass

### ISSUE THREAD

**Issue by ronilaukkarinen** [tyage/slack-patron#118]
For some reason I'm getting default fonts. Can you give me a quick instruction on how to apply for example `font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif` to body?

![slackpatron peikko us_CHANNELS_NOT_FOUND](https://user-images.githubusercontent.com/1534150/123872974-73dd1300-d93e-11eb-92cb-c33e7644db8f.png)

**Comment by tyage** [comment]
patching `app.less` is the easiest way.
https://github.com/tyage/slack-patron/blob/master/viewer/front/app.less
