### ISSUE TITLE
Ruby 2.4.0 no longer supports json 1.8.3

### ISSUE THREAD

**Issue by hokuto-k** [tyage/slack-patron#57]
Ruby 2.4.0 (current stable version) no longer supports json 1.8.3, so if the user use 2.4.0 `./viewer/setup.sh` will fail.

Workaround:
```
gem 'json'
```
to
```
gem 'json', github: 'flori/json', branch: 'v1.8'
```

(because v1.8.5 is compatible with Ruby 2.4.0.)

(素晴らしいツールをありがとうございます。）

**Comment by tyage** [comment]
Thank you for pointing out.
I will try to upgrade json gem to latest version (it maybe v2.0.3)
