### ISSUE TITLE
How do I get a backup from earlier version?

### ISSUE THREAD

**Issue by rattboi** [tyage/slack-patron#85]
I was using a version from ~Aug 15th, and just did a "git pull" and a "docker-compose down/up", and it seems my messages from before are gone. I assume they are still *somewhere* (I hope). Is there a method to import those messages back in?

**Comment by tyage** [comment]
I think my response is too late...
But you can import slack messages using slack export functions and ./bin/import.rb .

https://get.slack.help/hc/en-us/articles/201658943-Export-your-workspace-data
https://github.com/tyage/slack-patron#3-import-slack-backup-file
