### ISSUE TITLE
build fail: npm missing

### ISSUE THREAD

**Issue by ftc2** [tyage/slack-patron#89]
not sure what changed, but i don't think this will build anymore without explicitly choosing a package with npm.

it errors on `/viewer/setup.sh`

suggest specifying a package like `nodejs-npm` or `nodejs-current-npm` instead of `nodejs` here:
https://github.com/tyage/slack-patron/blob/master/viewer/Dockerfile#L14

**Comment by tyage** [comment]
fixed #90
